### ISSUE TITLE
Move tests to root

### ISSUE THREAD

**Issue by HGWright** [SciTools/python-stratify#100]
- [ ] move the tests
- [ ] ensure that `pytest` is still working i.e., you may need to change the config for `pytest` to tell it where the tests now live

**Comment by ocefpaf** [comment]
B/c this ships compiled code I see value in shipping the tests with the main module. One should be able to install a wheel and run the tests easily to ensure accuracy of the results in their own machine.

**Comment by bjlittle** [comment]
Awesome, happy to comply with this.

Actually, it makes total sense to keep the tests within the shipped code, particularly now that we've got the binary wheels building, testing and publishing for different `python` versions and platform architectures as part of the GHA CI.

I'm going to close this issue 👍 

You happy with that @HGWright ? (if not, then reopen this issue and we can discuss further)
