### ISSUE TITLE
Rationalise repo labels

### ISSUE THREAD

**Issue by bjlittle** [SciTools/python-stratify#106]
See https://github.com/SciTools/python-stratify/labels

**Comment by HGWright** [comment]
@bjlittle I don't see the value in having the "New: Pull Request" label. Surely it just applies to all new PR's, and isn't applied or removed automatically.

**Comment by bjlittle** [comment]
> @bjlittle I don't see the value in having the "New: Pull Request" label. Surely it just applies to all new PR's, and isn't applied or removed automatically.

@HGWright  Yeah, I kinda agree. I'd take the opportunity to purge any labels that exist and are never used.

I love the automation approach, as it's almost legitimizing the need for each label.

So tidy-up and purge as you see fit. Go for it!

At the end of the day, we can always reinstate a label if we eventually realise that it has genuine value.

**Comment by rcomer** [comment]
I think the "New: Pull Request" label was to help Peloton keep track of what we'd looked at.

**Comment by trexfeathers** [comment]
> I think the "New: Pull Request" label was to help Peloton keep track of what we'd looked at.

Yes, but despite best efforts we would reliably forget to remove the label once the pull request had been discussed. So over time ALL pull requests ended up with the label.

**Comment by HGWright** [comment]
Ok, the "New: Pull Request" label has been removed as it is no longer necessary. It is however used by some of the reusable workflows but I believe that would cause any problems as some other SciTools repos don't have the label but still use the workflows.
