### ISSUE TITLE
Request for contributor ORCIDs

### ISSUE THREAD

**Issue by HGWright** [SciTools/python-stratify#121]
## 📰 Custom Issue

Dear awesome `python-stratify` contributors!

`python-stratify` will soon be citable and contain a CITATION.cff file.

If you'd like to be recognised as a citable contributor then please share your [ORCID](https://orcid.org/) details in a comment in this issue, and I'll add them in batch to the CITATION.cff. Alternatively, if you want to raise a pull-request yourself instead after the CITATION.cff file goes up, then go for it... whatever you prefer 👍

If you don't want to add your details, then that's also totally fine too.

Regardless, thanks for the interest and contributions to `python-stratify`.

Hopefully, I've not missed anyone from the list:

- [x] @bjlittle 
- [x] @pelson 
- [x] @lbdreyer 
- [x] @trexfeathers 
- [x] @bouweandela 
- [x] @evertrol 
- [ ] @tjtg 
- [ ] @bayliffe 
- [x] @ocefpaf

**Comment by bjlittle** [comment]
@HGWright Awesome! Thanks for doing this.

My ORCID is [0000-0002-1345-9465](https://orcid.org/0000-0002-1345-9465) 👍

**Comment by bjlittle** [comment]
Also, take a peek at https://github.com/SciTools/nc-time-axis/blob/main/CITATION.cff

There are several contributors to `python-stratify` that have also contributed to `nc-time-axis` 👍

**Comment by bouweandela** [comment]
Mine is [0000-0001-9005-8940](https://orcid.org/0000-0001-9005-8940)

**Comment by trexfeathers** [comment]
[`0009-0000-6857-560X`](https://orcid.org/0009-0000-6857-560X)

**Comment by evertrol** [comment]
[0000-0001-8357-4453](https://orcid.org/0000-0001-8357-4453)
Thanks!

**Comment by lbdreyer** [comment]
Mine is 0009-0006-6310-3658

**Comment by ocefpaf** [comment]
Thanks! Mine is

0000-0003-4165-2913

**Comment by HGWright** [comment]
This has been up for almost a month, I am going to close this now. But if you would still like to be added, feel to either create an issue or a pr with your info.

Thanks everyone!
