### ISSUE TITLE
Caching of weights and indices

### ISSUE THREAD

**Issue by cpelley** [SciTools/python-stratify#17]
Interpolation is often utilised with high dimensional datasets.  It would be fantastic to be able to cache weights and indices and determine an API that has this usage in mind.

**Comment by cpelley** [comment]
Thanks @bbakernoaa

**Comment by bjlittle** [comment]
@cpelley Is this still a live desire?

**Comment by cpelley** [comment]
Hi @bjlittle, indeed though it's not on my priority list.

The code would require a significant redactor to support this.  The conservative approach is necessarily separate to the linear/nearest as the linear/nearest implementation is entirely cython.  To that end, it was my intention to first refactor the linear and nearest interpolation (stratify/_vinterp.pyx) so that it could be utilised by the same python code calling the conservative interpolation (stratify/_bounded_vinterp.py).  
This would then leave only performance sensitive code using cython and giving us the ability/flexibility to define a single user interface and more easily support cache utilisation.

**Comment by pp-mo** [comment]
@SciTools/peloton this still looks like it might have value, but we won't get around to it for some time yet!
We will probably do some planning sometime later this year.
Anything to add @cpelley ?

**Comment by cpelley** [comment]
Hi @pp-mo, no.  I'm afraid I have long since moved to different projects.  Thanks for the ping 👍

**Comment by pp-mo** [comment]
Well thanks, that's helpful.  We well might do this one day, but I'll close for now.
