### ISSUE TITLE
Stratify option to use float32

### ISSUE THREAD

**Issue by abooton** [SciTools/python-stratify#38]
Model precision means that model data often only needs to be of type float32 or int32 data.
However, vertical stratify is currently converting data to float64 for its calculations.  This is unnecessary for some usecases and too slow for some operational use cases.  

AC:
* Update stratify to accept and maintain data as float32.

See benfitzpatrick for more details.

**Comment by bjlittle** [comment]
@abooton Thanks 👍

**Comment by benfitzpatrick** [comment]
I tried converting to cython: floating (https://github.com/SciTools-incubator/python-stratify/compare/master...benfitzpatrick:float_32_preservation) but it didn't/doesn't work with the inheritance structure (fused type support + inheritance problem).

**Comment by pp-mo** [comment]
@SciTools/peloton reviewing this : leaving it open, but it won't happen for quite a while.
@benfitzpatrick  is this still of interest ?

**Comment by benfitzpatrick** [comment]
Still of interest, I reckon, but @s-boardman and @PaulAbernethy now better points of contact!

In general I think the Scientific Python community needs to make much more use of float32 wherever possible - faster, less memory, don't need the bits
