### ISSUE TITLE
Explore pspline option

### ISSUE THREAD

**Issue by pelson** [SciTools/python-stratify#5]
It would be super interesting to develop a pspline interpolator/extrapolator. 

For example: http://pypspline.sourceforge.net/

One major complexity is that interpolators/extrapolators currently assume that the input x,y are the same as the target x,y.

**Comment by pp-mo** [comment]
@SciTools/peloton no immediate prospect of this, with no-one really pushing for it, sadly. So we'll close for now.
@pelson is there anything you can add that might make this seem easier to aim at?
