### ISSUE TITLE
Add repo issue templates

### ISSUE THREAD

**Issue by HGWright** [SciTools/python-stratify#90]
Stratify > Insights > Community Standards

See [GitHub docs](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository)

**Comment by bjlittle** [comment]
@HGWright Awesome!

Looks great!

My only suggestion would be on the style choice on title capitalisation e.g., see https://www.grammarly.com/blog/capitalization-in-the-titles/

For `iris` we have:

![image](https://github.com/SciTools/python-stratify/assets/2051656/dc4d894c-c60e-4f1b-859a-597aabb10259)

Also, I'd suggest dropping the using of `template` in the `Custom issue template`:

![image](https://github.com/SciTools/python-stratify/assets/2051656/254cb6bc-3fe0-4f39-854a-ef86c6178101)

Also, akin to `iris`, you may want to also add links to the `python-stratify` GH Discussions. Your call 👍
